[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "shivarthu-client-tests"
version = "0.0.1"
description = ""
dependencies = [
    "selenium ==4.16.0",
    "webdriver-manager ==4.0.1",
]

[project.optional-dependencies]
dev = ["pytest ==7.4.3"]
